version: "3.2"
services:
  redis:
    restart: always
    image: redis:5
    ports:
      - "6379:6379"
    networks:
      - db-net

  db:
    restart: always
    image: mysql
    environment:
    - MYSQL_HOST=localhost
    - MYSQL_PORT=3306
    - MYSQL_ROOT_HOST=%
    - MYSQL_DATABASE=django
    - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3302:3306"
    networks:
      - db-net

  project:
    restart: always
    container_name: code
    command : bash -c "
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./Back/settings.ini
    build: 
      context: ./Back/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - db-net

  frontend:
    restart: always
    command : npm start
    container_name: front
    build:
      context: ./Front(typescript_ver)/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - project
    networks:
      - db-net

networks:
  db-net:
    driver: bridge
