# Generated by Django 4.1.6 on 2023-03-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("create_at", models.DateField(auto_now_add=True)),
                ("update_at", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("posts", "자유게시판"),
                            ("notices", "공지사항"),
                            ("suggest", "건의사항"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("content", models.TextField()),
                ("create_at", models.DateField(auto_now_add=True)),
                ("update_at", models.DateField(auto_now=True)),
            ],
        ),
    ]
