# Generated by Django 4.1.6 on 2023-04-04 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avator",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="rank",
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="my_profile"),
        ),
        migrations.AddField(
            model_name="user",
            name="rank",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userinfo",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
