# Generated by Django 4.1.6 on 2023-03-27 01:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="rank",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="score",
            field=models.FloatField(
                null=True, validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
    ]
