# Generated by Django 4.1.6 on 2023-04-04 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_avator_remove_userinfo_rank_user_avatar_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="avatar",
            new_name="avator",
        ),
    ]
