# Generated by Django 4.1.6 on 2023-04-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="video",
            field=models.FileField(null=True, upload_to="my_video"),
        ),
    ]
