# Generated by Django 4.1.6 on 2023-03-27 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userinfo_rank_userinfo_score"),
        ("analyses", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysis",
            name="rank",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="score",
        ),
        migrations.AddField(
            model_name="analysis",
            name="info",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.userinfo",
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="video",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
