# Generated by Django 4.1.6 on 2023-03-27 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userinfo_rank_userinfo_score"),
        ("analyses", "0003_remove_analysis_rank_remove_analysis_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.userinfo",
            ),
        ),
    ]
